### ISSUE TITLE
YAML pipelines not supported

### ISSUE THREAD

**Issue by vladnega** [raul-arrieta/Terraform-Outputs#4]
I'm having issues running the terraform-outputs task using Azure Pipelines (YAML). I guess it's because the **id** of the task has a dash (`-`) in it.

Here's a snippet of my YAML file:

```yml
  - deployment: post_provision_tasks
    displayName: 'Post provision tasks'
    pool: Hosted Windows 2019 with VS2019
    environment: test-$(ng_build_environment)
    dependsOn: ''
    strategy:
      runOnce:
        deploy:
          steps:
          - task: terraform-outputs@0
            displayName: 'Terraform Outputs'
            inputs:
              workingDirectory: '$(Pipeline.Workspace)/terraform'
```

Here's the error that I'm getting from the Azure DevOps pipeline:

>  Job Job1: Step terraform-outputs has an invalid name. Valid names may only contain alphanumeric characters and '_' and may not start with a number.

Would it be possible to create a version of this task without the `-` in the **id**?

**Comment by raul-arrieta** [comment]
Hi @vladnega,
Is this still happening to you?
Could you please attach a yaml to reproduce the above scenario?

I executed this pipeline without any problem: 🤔 

```yml
trigger:
- master

jobs:
- job:
  displayName: Hosted Ubuntu 1604
  pool:
    name: Hosted Ubuntu 1604

  steps:

  - task: TerraformCLI@0
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/tf_scripts/'
      environmentServiceName: 'AzureMPN_Raul'
      commandOptions: ' -auto-approve'

  - task: terraform-outputs@0
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)/tf_scripts/'

- job:
  displayName: Hosted VS2017
  pool:
    name: Hosted VS2017

  steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '0.11.11'

  - task: TerraformCLI@0
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/tf_scripts/'
      environmentServiceName: 'AzureMPN_Raul'
      commandOptions: ' -auto-approve'

  - task: terraform-outputs@0
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)/tf_scripts/'

- job:
  displayName: Hosted Windows 2019 with VS2019
  pool:
    name: Hosted Windows 2019 with VS2019

  steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '0.11.11'

  - task: TerraformCLI@0
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/tf_scripts/'
      environmentServiceName: 'AzureMPN_Raul'
      commandOptions: ' -auto-approve'
    
  - task: terraform-outputs@0
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)/tf_scripts/'


- job:
  displayName: Hosted macOS
  pool:
    name: Hosted macOS

  steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '0.11.11'

  - task: TerraformCLI@0
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/tf_scripts/'
      environmentServiceName: 'AzureMPN_Raul'
      commandOptions: ' -auto-approve'

  - task: terraform-outputs@0
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)/tf_scripts/'

- job:
  displayName: Hosted macOS High Sierra
  pool:
    name: Hosted macOS High Sierra

  steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '0.11.11'

  - task: TerraformCLI@0
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/tf_scripts/'
      environmentServiceName: 'AzureMPN_Raul'
      commandOptions: ' -auto-approve'

  - task: terraform-outputs@0
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)/tf_scripts/'

```

Thanks! 😊
